name: Update Docker image
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: fiews/cl-eth-failover
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          tag_semver: true
